[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=docker-php-entrypoint php-fpm
autostart=true
autorestart=true
priority=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

# ==========================================
# 1. TRABAJADORES DE COLAS (QUEUE WORKER)
# ==========================================
[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work --queue=default
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
# Ejecutar como www-data, el mismo usuario que configuramos en tu Dockerfile
user=www-data
numprocs=1
# --- LA MAGIA PARA VER LOS LOGS EN DOCKER ---
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

# ==========================================
# 2. LARAVEL REVERB (WEBSOCKETS)
# ==========================================
# [program:laravel-reverb]
# process_name=%(program_name)s_%(process_num)02d
# # Es crítico usar --host=0.0.0.0 para que Reverb acepte conexiones desde fuera del contenedor
# command=php /var/www/html/artisan reverb:start --host="0.0.0.0" --port=8080
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# user=www-data
# numprocs=1
# # --- LA MAGIA PARA VER LOS LOGS EN DOCKER ---
# stdout_logfile=/dev/stdout
# stdout_logfile_maxbytes=0
# stderr_logfile=/dev/stderr
# stderr_logfile_maxbytes=0

#===========================================
# 3. LARAVEL SCHEDULER (TAREAS PROGRAMADAS)
#===========================================
[program:schedule-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan schedule:work 
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
# --- LA MAGIA PARA VER LOS LOGS EN DOCKER ---
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0