[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php]
command=%(ENV_SUPERVISOR_PHP_COMMAND)s
user=%(ENV_SUPERVISOR_PHP_USER)s
environment=LARAVEL_SAIL="1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

# ==========================================
# 1. TRABAJADORES DE COLAS (QUEUE WORKER)
# ==========================================
[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work --queue=default
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
# Ejecutar como sail, el mismo usuario que configuramos en tu Dockerfile
user=sail
numprocs=1
# --- LA MAGIA PARA VER LOS LOGS EN DOCKER ---
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0


# [program:queue-worker-tickets-notifications]
# process_name=%(program_name)s_%(process_num)02d
# command=php /var/www/html/artisan queue:work --queue=tickets-notifications
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# # Ejecutar como sail, el mismo usuario que configuramos en tu Dockerfile
# user=sail
# numprocs=1
# # --- LA MAGIA PARA VER LOS LOGS EN DOCKER ---
# stdout_logfile=/dev/stdout
# stdout_logfile_maxbytes=0
# stderr_logfile=/dev/stderr
# stderr_logfile_maxbytes=0

; [program:queue-worker-tickets]
; process_name=%(program_name)s_%(process_num)02d
; command=php /var/www/html/artisan queue:work --queue=tickets
; autostart=true
; autorestart=true
; stopasgroup=true
; killasgroup=true
; # Ejecutar como sail, el mismo usuario que configuramos en tu Dockerfile
; user=sail
; numprocs=1
; # --- LA MAGIA PARA VER LOS LOGS EN DOCKER ---
; stdout_logfile=/dev/stdout
; stdout_logfile_maxbytes=0
; stderr_logfile=/dev/stderr
; stderr_logfile_maxbytes=0


[program:queue-worker-reports]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work --queue=reports --memory=6144
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
# Ejecutar como sail, el mismo usuario que configuramos en tu Dockerfile
user=sail
numprocs=1
# --- LA MAGIA PARA VER LOS LOGS EN DOCKER ---
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

# [program:queue-worker-sync]
# process_name=%(program_name)s_%(process_num)02d
# command=php /var/www/html/artisan queue:work --queue=sync
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# # Ejecutar como sail, el mismo usuario que configuramos en tu Dockerfile
# user=sail
# numprocs=1
# # --- LA MAGIA PARA VER LOS LOGS EN DOCKER ---
# stdout_logfile=/dev/stdout
# stdout_logfile_maxbytes=0
# stderr_logfile=/dev/stderr
# stderr_logfile_maxbytes=0

# ==========================================
# 2. LARAVEL REVERB (WEBSOCKETS)
# ==========================================
# [program:laravel-reverb]
# process_name=%(program_name)s_%(process_num)02d
# # Es crítico usar --host=0.0.0.0 para que Reverb acepte conexiones desde fuera del contenedor
# command=php /var/www/html/artisan reverb:start --host="0.0.0.0" --port=8080
# autostart=true
# autorestart=true
# stopasgroup=true
# killasgroup=true
# user=sail
# numprocs=1
# # --- LA MAGIA PARA VER LOS LOGS EN DOCKER ---
# stdout_logfile=/dev/stdout
# stdout_logfile_maxbytes=0
# stderr_logfile=/dev/stderr
# stderr_logfile_maxbytes=0

#===========================================
# 3. LARAVEL SCHEDULER (TAREAS PROGRAMADAS)
#===========================================
[program:schedule-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan schedule:work 
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=sail
numprocs=1
# --- LA MAGIA PARA VER LOS LOGS EN DOCKER ---
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0